const HOME_DATA  = 
  {
    "intro":"The next step is to begin tracking your sleep patterns. Please take a few minutes to fill out a sleep diary each morning for the next 2 weeks. This lets us know your starting point. If you forget to record your answers one morning, you can go back and fill them in up to a day later.",
    "subhead1":"Sleep diary instructions:",
    "intro1":"The sleep diary is very brief. It should only take a few minutes to complete. If you don’t know the exact times, record your best guess.",
    "bullet1":"•	Record the time you got into bed.",
    "bullet2":"•	Record the time you began to try to fall asleep.",
    "bullet3":"•	Estimate the time when you fell asleep.",
    "bullet4":"•	Record how many times you woke up during the night.",
    "bullet5":"•	Record how long you were awake each time.",
    "bullet6":"•	Record the time you woke up and stayed awake.",
    "bullet7":"•	Record the time you got out of bed to start your day. This should be after your final awakening.",
    "bullet8":"•	Rate the overall quality of your sleep.",
    "bullet9":"•	Note any medications or other sleep aids taken before going to bed.",
    "description":"Please fill out a sleep diary each day. It is best to do this as soon as you get out of bed so that you don’t forget.",
    "disclaimerTxt":"This device in no way replaces decisions made by or the treatment plan given to you by your healthcare provider. The Health enSuite Insomnia App will only be used to assist your healthcare provider support a deprescribing decision or refer you to cognitive behavioural therapy.",
  };

  const LEVEL1_DATA = 
  {
    "splashBullet1": "You will see that new information is available to you within the Health enSuite app.",
    "splashBullet2": "Health enSuite Insomnia consists of a series of levels or content chapters. Each level has tasks you will need to complete before you can advance to the next level. These tasks include reading about new strategies for improving your sleep, watching videos, answering questions, completing daily sleep diaries, and tracking your medications. Each level is designed to take about one week to complete so that by the end of 6 weeks you will have completed the entire program.",
    "bullet1": "Health enSuite Insomnia is designed to support you in changing your habits and improving your sleep. The advice it contains should complement, but does not replace, the services you receive from your health care provider.",
    "bullet2": "The main goals for this first week are for you to continue tracking your sleep patterns using the sleep diaries, and learn about some of the common causes and consequences of insomnia.",
    "bullet3": "It may also be time to start reducing your use of sleeping pills. Follow the medication schedule recommended by your health care provider.",
    "subHead1": "To advance to the next level you will need to:",
    "bullet4": "- Complete at least 5 sleep diaries within a week",
    "bullet5": "- Complete the readings and activities for level 1 (Introduction to Health enSuite)",
    "bullet6": "Insomnia is more than just getting a poor night’s sleep. Everyone can have difficulty sleeping from time to time. For people with insomnia, difficulty sleeping becomes a regular and persistent problem. This could involve difficulty falling asleep, difficulty staying asleep, or both. Some people with insomnia wake up frequently throughout the night and have trouble getting back to sleep. Others wake up too early in the morning.",
    "bullet7": "Insomnia is not the result of a lack of opportunity to sleep. People with insomnia experience sleep disruptions even though they had a reasonable chance to sleep.",
    "subHead2": "Which of the following best describes your situation (check all that apply):",
    "bullet8": "Usually, insomnia is not caused by a chemical imbalance. Most of the time it is caused by habits, lifestyle, and problematic ways of thinking about sleep. Solutions that focus on these underlying causes of insomnia have the best chance of long-term success.",
    "bullet9": "Sometimes medical conditions interfere with sleep. If these are left untreated, changes to your sleep routine might not be enough. Talk with your health care provider about any medical conditions you may have that may be affecting your sleep.",
    "bullet10": "Health enSuite Insomnia is based on a cognitive behavioural approach to treating insomnia. The goal is to change old ways of thinking and behaving and learn new, more effective ways of thinking and behaving. Every week, you will learn new skills to help you sleep better at night and feel better during the day. Here is an outline of what to expect in the weeks to come.",
    "topic1": "Introduction to Health enSuite Insomnia (this week)",
    "topic2": "Introduction sleep restriction therapy and using the sleep restriction clock",
    "topic3": "Changing behaviours and improving sleep hygiene",
    "topic4": "Relaxation techniques",
    "topic5": "Changing negative thoughts related to sleep",
    "topic6": "Setback prevention and planning for the future",
    "bullet11": "It may take a few weeks before you start to notice a difference in your sleep quality. Don’t get discouraged. Changing habits can be difficult and take time. The key to success is to stick with the program and practice the skills you are learning every day.",
    "bullet12": "Sleeping pills may seem like an easy way to manage your sleep. Unfortunately sleeping pills only work as a short term remedy for sleep problems. After a few weeks, sleeping pills can become less effective in promoting good sleep. But many people continue using sleeping pills for weeks or even years. This can happen even when there are adverse side effects like daytime drowsiness and difficulty concentrating.",
    "bullet13": "Your health care provider has recommended a plan that will gradually reduce the amount of the sleeping pills you are taking. The goal is for you to eventually be able to stop taking sleeping pills and get a good night’s sleep.",
    "bullet14": "How is it going so far?",
    "subHead3": "Which of the following best describes your feelings about this plan?",
    "bullet15": "Sudden changes in medications increase your risk of withdrawal symptoms.",
    "bullet16": "The risk of withdrawal symptoms is reduced when medication changes are slow and gradual. The plan your health care provider has recommended takes this slow, gradual approach. Your sleeping pill dose is reduced slowly over a period of many weeks or months. A small change happens each time you start a new dose.",
    "bullet17": "You might find that your insomnia initially gets worse after you reduce your medication. Try your best to stick to the medication plan even if this happens. Over time, your body will adjust to the new dose. It should get easier within a few days.",
    "bullet18": "Sometimes people think that they need the pills to sleep. This is a myth.",
    "bullet19": "Even if your sleep problems initially get worse when you reduce your medications, this does not mean that you will never be able to sleep well without taking medication.",
    "bullet20": "Over the next few weeks you will learn strategies for managing your sleep that will make it possible for you stop taking sleeping pills and get a good night’s sleep.",
    "bullet21": "Having someone to support you can make changing your thoughts and behaviours easier. Is there someone who can support you? This could be a romantic partner, family member, friend or someone else you feel supports you. If you regularly share a bed with another person, it is good idea to involve this person. They can play an important role in helping you change your routines around sleep.",
    "radioQ1": "Which of these best describes your situation? (Choose the option that describes your typical sleeping arrangement)",
    "radioQ2": "Would you like to nominate a support person to help you throughout this program? This person will be sent tips and information related to the skills you are learning.",
    "radioQ3": "Would you like to nominate your roommate to support you throughout this program? This person will be sent tips and information related to the skills you are learning.",
    "radioQ4": "",
    "subHead4": "Things to do this week:",
    "bullet22": "Use the sleep diary to track when you go to bed at night and when you get up in the morning. Record your sleep quality each day. Note the dose of any medications you are taking. To advance to the next level you will need to complete at least 5 of these entries.",
    "bulletLastPsycho": "You might find that your insomnia initially gets worse after you reduce your medication. Try your best to stick to the medication plan even if this happens. Over time, your body will adjust to the new dose.",
    "splashBullet3": "In level 2 you will learn about a technique called sleep restriction.",
    "splashBullet4": "To advance to level 3 you will need to:",
    "splashBullet5": "• Complete “Introduction to Sleep Restriction”. This includes setting up your sleep clock.",
    "splashBullet6": "• Complete at least 5 sleep diaries within a week.",
    "splashBullet7": "• Complete the self-assessment of current insomnia symptoms.",
    "bullet23": "The main goal this week is to start using a strategy called sleep restriction.",
    "bullet24": "Sleep restriction involves changing the times you get into bed at night and get out of bed in the morning to make your sleep more efficient. The aim is to restrict the amount of time you spend lying in bed awake, not sleeping.",
    "bullet25": "You might think that the more time you spend in bed, the more likely you will be to get a good night’s sleep. This is not the case. If you spend a lot of time lying awake at night you will begin to associate the bed with being awake. Your bed should be a place for sleep.",
    "subHead5": "Some things you can do to associate your bed with sleep:",
    "bullet26": "• Try using your bed only for sleeping (and sex). Get into bed only when you feel sleepy.",
    "bullet27": "• Avoid reading, watching TV, or using screens (phone, computer, etc.) while in bed.",
    "bullet28": "• If you don’t fall asleep within 20 minutes, get out of bed and do something else. Go back to bed only when you feel tired.",
    "subHead6": "The first step is to look at your current sleep patterns. Based on your last 7 sleep diaries:",
    "bullet29": "• You spent an average of in bed per night.",
    "bullet30": "• You were asleep for an average of per night.",
    "bullet31": "Sleep efficiency is the ratio of time in bed that is spent asleep.",
    "bullet32": "The goal this week is to use the information from your sleep diaries to build a plan that will improve your sleep efficiency.",
    "bullet33": "The next step is to choose a sleep window for the next week.",
    "bullet34": "Starting this week, use the sleep clock to establish a consistent bed time and rise time for yourself. This means going to bed and getting out of bed at the same time every day – including weekends. It might be tempting to change your sleep patterns on the weekend, but this habit may be making your sleep problems worse. Going to bed and getting up at the same time everyday helps make it easier to feel sleepy when it is time to sleep.",
    "subHead7": "Select your rise time:",
    "bullet35": "Pick a rise time you can maintain for the next 7 days. It needs to be a time that will work for you and allow you to start your daily activities on time.",
    "bullet36": "For the next week, your target will be to get 5 hours of sleep per night.",
    "bullet37": "Based on the rise time you selected, here is your new bed time and rise time for the next week. Please do your best to stick to this schedule.",
    "bullet38": "This app can be used to set alarms on your phone to remind you when it is time to get ready for bed and get up in the morning.",
    "bullet39": "An important part of this therapy involves maintaining consistent bed times and rise times. Please do your best to maintain this for the next week. Your sleep window will be adjusted as you progress through the program and as your sleep efficiency increases.",
    "bullet40": "You might feel like your new bed time is much later than you would normally go to bed. It might seem extremely late to you. This is normal. The goal is to limit your time in bed to the time you spend sleeping. Rather than spending a lot of time in bed awake before falling asleep, now you will go to bed later when you are more likely to feel sleepy.",
    "bullet41": "Sleep restriction can be difficult at first. You may have a few nights with only a few hours of sleep. When this happens many people try to compensate by sleeping in later or taking a nap during the day. Don’t do this – stick to the schedule! The restricted sleep schedule is designed to increase your sleep drive. This means that it will be easier to fall asleep as you train your body to expect sleep at the same time every day.",
    "bullet42": "Sleep efficiency describes how much of the time you spend in bed is actually spent sleeping.",
    "bullet43": "Each week your sleep window will be adjusted based on how efficient your sleep was over the past week.",
    "bullet44": "Sleep efficiency less than 85% means there is room for improvement. To increase sleep efficiency, your sleep window will be reduced by moving your bed time 15 minutes later.",
    "bullet45": "Sleep efficiency between 85%-89% means you are right on track. With scores like this your sleep window should stay the same.",
    "bullet46": "Sleep efficiency between 90%-94% is a great result. At this point, you can extend your sleep window by moving your bed time 15 minutes earlier.",
    "bullet47": "If your sleep efficiency is consistently over 95%, it might be too high. This can sometimes mean that you are not getting enough sleep. With a result like this, your sleep window will be increased by 30 minutes.",
    "subHead8": "Things to do this week:",
    "bullet48": "• Track your sleep and medication use each day.",
    "bullet49": "• Follow your sleep clock. Set alarms to remind you when it is time to get ready for bed and get up each morning.",
    "bullet50": "• Complete the self-assessment of your current insomnia symptoms.",
    "splashBullet8": "In level 3 you will continue using the sleep clock to improve your sleep efficiency. The new readings and activities this week focus on sleep hygiene.",
    "splashBullet9": "To advance to level 4 you will need to:",
    "splashBullet10": "• Review your sleep clock settings. Make adjustments if needed.",
    "splashBullet11": "• Complete “Sleep Hygiene Checklist” at least once.",
    "splashBullet12": "• Complete at least 5 sleep diaries within a week.",
    "bullet51": "Sleep hygiene rules are tips for maintaining good sleep health. You may have heard some of these tips before. Although sleep hygiene alone might not be enough to resolve chronic insomnia, it is important to address behaviours that are obviously interfering with good sleep. Improving sleep hygiene can be a key step on the way to a good night’s sleep.",
    "bullet52": "Use the Sleep Hygiene Checklist to keep track of the things you are doing during the day, before going to bed, and when you are in bed to help you sleep well. Some people find it helpful to set themselves reminders to remember to practice the things that are especially helpful for them.",
    "bullet53": "Sleep hygiene checklist",
    "subHead9": "Check off the things you have done today:",
    "bullet54": "Use your bed only for sleeping: Don’t use your bed as a place to watch TV, eat, read, work on your laptop, pay bills, etc.",
    "bullet55": "Get up and try again if you don’t fall asleep within 15-20 minutes: Get up and do something calming or boring until you feel sleepy, then go back to bed and try again. Avoid turning on bright lights or doing anything that is too stimulating or interesting. This could wake you up even more.",
    "bullet56": "Don’t take naps: If you can’t make it through the day without a nap, keep it under 1 hour and before 3pm.",
    "bullet57": "Exercise regularly, but not right before bed: Getting regular exercise that raises your heart rate and gets you to sweat a little can be a great way to improve your sleep. Exercising in the evening can make it more difficult to relax when it is time to go to sleep. Try exercising in the mornings instead.",
    "bullet58": "Eat right: Feeling hungry or too full can make it more difficult to fall asleep. Try to avoid having a heavy meal right before bed. If you feel hungry, try having a light snack.",
    "bullet59": "Avoid stimulants: It is not a good idea to have caffeine, nicotine, or other stimulants 4-6 hours before going to bed. If you drink coffee or tea try to keep it early in the day.",
    "bullet60": "Avoid alcohol: Many people believe that alcohol helps them to relax and get to sleep more easily, but it actually leads to poorer quality sleep. It is best to avoid drinking alcohol 4-6 hours before bed.",
    "bullet61": "Create a comfortable space: Make sure your room is not too hot or too cold. Use earplugs to block out noise and an eye mask or curtains to block out the light.",
    "bullet62": "Limit screen time before bed: Stop watching TV or working on your computer at least one hour before bed time. Set your phone to night mode (do not disturb) and keep it away from your bed. This will decrease the temptation to use it while you are trying to sleep.",
    "bullet63": "Create a routine to help you unwind: Many people find it helpful to do some stretching or deep breathing to help them relax before bed. This can also be a time to work through your thoughts and worries before bed. Try write them down so that you can deal with them in the morning.",
    "splashBullet13": "In level 4 you will continue using the sleep clock to improve or maintain your sleep efficiency. The new section this week focuses on relaxation techniques. Try adding one of these to your nightly routine.",
    "splashBullet14": "To advance to level 5 you will need to:",
    "splashBullet15": "• Review your sleep clock settings. Make adjustments if needed.",
    "splashBullet16": "• Read the Relaxation Techniques section. Try out at least one of the techniques.",
    "splashBullet17": "• Complete at least 5 sleep diaries within a week.",
    "splashBullet18": "• Complete the self-assessment of current insomnia symptoms.",
    "bullet64": "Relaxation of one the core components of cognitive behavioral therapy for insomnia. Relaxation techniques include things you can do to reduce tension and stress as a way to promote better sleep. If you are not already doing so, we encourage you to try adding relaxation techniques to your nightly routine.",
    "subHead10": "You can choose from a variety of techniques:",
    "bullet65": "• progressive muscle relaxation",
    "bullet66": "• deep breathing",
    "bullet67": "• meditation",
    "bullet68": "• stretching or yoga",
    "bullet69": "• listening to relaxing sounds or soft music",
    "bullet70": "• aromatherapy",
    "bullet71": "• gentle massage",
    "subHead11": "Stress and insomnia",
    "bullet72": "Stress is one of the most common triggers for insomnia. Relaxation helps decrease the physical signs of stress such as increased heart rate, blood pressure, breathing rate, and muscle tension. It also increases positive feelings of calmness and peacefulness.",
    "bullet73": "Do you notice a relationship between how stressed you are feeling and your ability to get a good night’s sleep? Your sleep diary can be a useful tool for helping you notice these kinds of patterns. Even if stress is not a major trigger for your insomnia, relaxation can still be useful in helping you unwind.",
    "bullet74": "This app contains some information and videos to introduce you to some common relaxation techniques. Your aim should be to adopt one or more of these relaxation strategies and make them a part of your daily nighttime routine.",
    "subHead12": "Progressive Muscle Relaxation",
    "bullet75": "Progressive muscle relaxation involves systematically contracting specific muscle groups for a few seconds and then releasing them. Starting with your toes and feet, you can move through all the major muscle groups in your body, tensing and relaxing as you go. Pay attention to how your muscles feel as you release and relax them. With practice, you will learn to notice the difference between tensed and relaxed muscles.",
    "bullet76": "Choose a quiet place where you can sit comfortably or lie down. It is a good idea to set aside about 15 minutes for the entire exercise.",
    "bullet77": "Start at your feet and slowly move up to your head. Tense and relax each muscle group for 3 to 6 seconds each. Move from the feet and toes, to the knees, thighs, glutes, abdomen, chest, hands, arm, shoulders, neck, jaw, muscles around the eyes, and forehead. Be careful not tense your toes and feet too vigorously. This can sometimes cause painful muscle cramps.",
    "bullet78": "Maintain calm, slow breathing throughout the exercise. As you tense you muscles, breathe in through your nose. As you release your muscles, breathe out through your mouth.",
    "bullet79": "At the end of progressive muscle relaxation exercises, you will feel calm and relaxed ready for a sound peaceful sleep.",
    "bullet80": "Here are some videos that demonstrate the progressive muscle relaxation technique. You can use them to help you practice the technique.",
    "bullet81": "Please note these videos will use your mobile or Wi-Fi data for streaming.",
    "subHead13": "Passive muscle relaxation",
    "bullet82": "When you are able to notice the difference between tensed and relaxed muscles you can use this strategy. It is similar to the progressive muscle relaxation strategy, except that you do not have to tense your muscles first. Instead, you notice when your muscles are tense and focus on releasing the tension.",
    "bullet83": "It is a quick and easy way to relax any time or place.",
    "bullet84": "Breathing usually occurs naturally without much thought. A number of relaxation techniques involve taking a moment to focus on your breath. One strategy is to breathe from your belly rather than your chest. When you breathe in your chest, only a part of your lungs are filled. Your breath is shallower and your heart rate is faster. In contrast, belly breathe makes it easier to take slow deep breaths.",
    "bullet85": "Belly breathing is deep, fills your lungs with air, and is better for relaxation than chest breathing. Most people do not use belly breathing, but you can learn to do this with practice.",
    "subHead14": "Give it a try!",
    "bullet86": "Lie down or sit comfortably.",
    "bullet87": "Place one hand on your chest and the other hand on your belly.",
    "bullet88": "Take a slow, deep breath in through your nose. Feel your stomach push against your hand as air fills the deepest part of your lungs. Your chest should remain as still as possible.",
    "bullet89": "Breathe out through your mouth. Push the air out by tightening your stomach muscles.",
    "bullet90": "Continue breathing in and out in this way for about 5 to 10 minutes. You should feel your belly rise and fall with each breathe.",
    "bullet91": "You find it difficult to breathe through your belly at first. With practice your diaphragm and the other muscles you are using will get stronger. Eventually, you may be able to use this technique without placing your hands on your belly.",
    "bullet92": "This strategy relies on your ability to focus and imagine that you are getting relaxed. You will experience relaxing sensations by repeating suggestions to yourself, such as “my arm is heavy,” “my breathing is calm”.",
    "bullet93": "his audio recording is a guided relaxation exercise that uses this strategy.",
    "subHead15": "How do I add relaxation strategies to my life?",
    "bullet94": "Relaxation strategies can be used before bed to help you unwind, or throughout the day to help you manage stressful events. Setting aside 15 to 20 minutes shortly before your bedtime is a great way to add these techniques into your sleep routine.",
    "bullet95": "You may even try yoga or meditation to relax and reduce your stress. You may find you like one strategy more than others. The key is to choose something that works for you.",
    "splashBullet19": "In level 5 you will continue using the strategies you have learned to improve or maintain your sleep quality and efficiency. The new section this week focuses on changing thoughts that interfere with good sleep.",
    "splashBullet20": "To advance to level 6 you will need to:",
    "splashBullet21": "• Review your sleep clock settings. Make adjustments if needed.",
    "splashBullet22": "• Complete the chapter called Changing Thoughts.",
    "splashBullet23": "• Complete at least 5 sleep diaries within a week.",
    "bullet96": "So far we have focused on changing your behaviours and routines related to sleep. For some people it is also important to change the way they think about sleep. This section focuses on strategies for changing some commonly held misconceptions.",
    "bullet97": "Unhelpful thoughts can happen automatically, outside of awareness. The first step to changing these thoughts is to begin to notice them when they happen. The next step is to try replacing unhelpful thoughts with more helpful alternatives.",
    "bullet98": "Let’s consider Mary’s situation. She finds herself awake at 3:00a.m. She is worried about her ability to function tomorrow.",
    "thought1": "“I need to find a way to fall asleep. I won’t be able to function tomorrow.”",
    "subHead16": "What are some more helpful ways of thinking about her situation?",
    "bullet99": "She thinks about the evidence that supports her beliefs. She remembers that she has been able to function after a poor night’s sleep in the past. This allows her to replace her unhelpful thoughts with more helpful ones:",
    "thought2": "“There is no point worrying about this now. Sometimes I can still function after a poor night’s sleep.”",
    "bullet100": "Let’s try challenging some other examples of thoughts people with insomnia commonly believe.",
    "thought3": "“It is necessary to get at least 8 hours of sleep each night.”",
    "bullet101": "Some people feel refreshed after 7 or 8 hours, but others thrive with only 6.5 hours. The amount of sleep we need varies from person to person. Trying to achieve unrealistic goals generally just increases feelings of worry and anxiety. Your sleep reports can help determine what a realistic expectation is for you.",
    "thought4": "“I should be able to wake up feeling refreshed and full of energy every day.”",
    "bullet102": "Energy levels vary from day to day. Even sound sleepers occasionally wake up without feeling completely rested. It is normal to have days when you don’t feel fully refreshed.",
    "thought5": "“My partner falls asleep as soon as his or her head hits the pillow and stays asleep throughout the night. I should be able to do that too.”",
    "bullet103": "Everyone is different. Just because one person can fall asleep and stay asleep easily doesn’t mean it will be that way for everyone else. Instead of focusing on other people, try to remember the strategies that have helped you improve your sleep.",
    "bullet104": "Sleep doesn’t have to limit your daytime activities",
    "thought6": "“I feel irritable, depressed, or anxious during the day because I did not sleep well last night.”",
    "bullet105": "Sleep is one reason for being in a bad mood, but there are lots of other reasons too. Work, health, and relationships are other common sources of stress that affect how we feel throughout the day. Blaming sleeplessness for all difficulties in daytime functioning is not particularly helpful.",
    "textTitle1": "A more realistic expectation might be:",
    "textTitle2": "Are there other reasons someone might feel irritable, depressed, or anxious?",
    "textTitle3": "What are some other ways of managing after a poor night’s sleep?",
    "textHint1": "Enter a realistic expectation",
    "textHint2": "Enter other reasons",
    "textHint3": "Enter other ways",
    "thought7": "“I need to avoid or cancel important social and family obligations after a poor night’s sleep. This is the only way I can manage the results of a poor night’s sleep.”",
    "bullet106": "Changing your plans based on how well you slept can mean that you miss out on important parts of life. Someone who does this often may find that his or her entire life begins to be organized around sleep.",
    "bullet107": "Try not to place too much emphasis on sleep. Instead, focus on doing the things you enjoy even if your sleep wasn’t perfect the night before.",
    "bullet108": "Have you ever felt this way? The problem here is that lying awake trying to sleep rarely makes it easier fall asleep. This way of thinking also tends to make people feel helpless. As if there is nothing they can do to improve their sleep. This is simply not true. The key is to try the right things. If you can’t fall asleep within 15 minutes, try getting out of bed to do something else. Continue practicing the techniques you have learned so far (sleep restriction, sleep hygiene, relaxation, etc.).",
    "subHead17": "Strategies to practice",
    "bullet109": "Did any of these examples seem especially true for you? Maybe these are thoughts you have had in the past. Maybe you have other negative thoughts you would like to change. Practice challenging the unhelpful thoughts you have in your everyday life.",
    "subHead18": "Ask yourself:",
    "bullet110": "• What is the evidence that supports this idea?",
    "bullet111": "• What is the evidence against this idea?",
    "bullet112": "• Is there another explanation?",
    "bullet113": "• What is the worst that could happen? Could I live with that?",
    "bullet114": "• What is the best that could happen?",
    "bullet115": "• What is the most realistic outcome?",
    "bullet116": "• What would I tell a friend if he or she was in the same situation?",
    "splashBullet24": "• Complete at least 5 sleep diaries within a week.",
    "bullet117": "People sometimes worry that improvements in their sleep will not last. This can be especially true for someone who has struggled with insomnia for many years. Don’t let this fear derail your progress.",
    "bullet118": "It is normal to have a poor night’s sleep from time to time. You might encounter setbacks, but you now have skills you can use to manage these challenges. You will never be back at “square one”.",
    "bullet119": "Take a moment to reflect on what a setback might look like for you. Are you worried you will have a bad night’s sleep? Are you afraid of having a totally sleepless night or several bad nights in a row? Write down what you think will happen.",
    "textHint4": "Enter your response here",
    "bullet120": "Now think about what you can do if this happens. Use the strategies that have helped you improve your sleep so far.",
    "textHint5": "Enter your strategy here",
    "subHead19": "These strategies might include:",
    "bullet121": "• Staying up past your normal bed time to increase sleep drive.",
    "bullet122": "• Going to bed and waking up at the same time every day.",
    "bullet123": "• Tracking your sleep using the sleep diary.",
    "bullet124": "• Using your sleep clock to increase sleep efficiency.",
    "bullet125": "• Using the sleep hygiene checklist.",
    "bullet126": "• Only going to bed when you feel sleepy.",
    "bullet127": "• Getting out of bed if you don’t fall asleep within 20-30 minutes",
    "bullet128": "• Relaxation techniques",
    "bullet129": "• Avoiding “all or nothing” thinking",
    "bullet130": "• Reminding yourself that one bad night does not mean you will have a string of bad nights.",
    "bullet131": "• Remembering that you can function tomorrow even if you had a poor night’s sleep.",
    "bullet132": "There can be setbacks as you work towards the goal of sleeping drug-free. Talk with your health care provider about your plan for reducing your use of sleeping pills and discuss any modifications as needed. It is better to modify your plan rather than abandoning it altogether. You might need to adjust the plan because of withdrawal symptoms or events in your life like an especially stressful period at work.",
    "bullet133": "Over the last few weeks you have learned a lot of new strategies to manage your sleep. You can continue to use any of the tools within the Health enSuite app to help support your improved sleep habits.",
    "bullet134": "Over the next few weeks you will learn strategies to help resolve this problem.",
    "bullet135": "",
  };

  var hours = ['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18'];

  const CONTACT_DATA  =
  {
    "email":"TeamHealthEnSuite@iwk.nshealth.ca",
    "phoneNumbers":"(902) 470 7934",
    "tollFree":"Toll-free number: 1-877-341-8309 press 5",
  };
